site_name: GIZA

repo_name: "ZS"
repo_url: "https://github.com/HeitorQueAnd/ZS"

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Dark mode
      primary: green
      accent: green
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light mode
      primary: green
      accent: green

markdown_extensions:
  - attr_list
  - tables

extra_css:
  - custom.css

nav:
  - Início: index.md
  - Templates:
      - Roteiro Discovery: template/roteiro.md
      - Roteiro Teams: template/teams.md
  - Módulos:
      - Newave:
          - Discovery:
              - 23/06 - Ruídos: modulos/newave/discovery/ruidos.md
              - 22/07 - Emissões Atmosféricas: modulos/newave/discovery/emissoes.md
          - Elicitação de Requisitos:
              - Emissões Atmosféricas: modulos/newave/elicitacao/emissoes.md
              - Ruídos: modulos/newave/elicitacao/ruidos.md
              - Erosão: modulos/newave/elicitacao/erosao.md
          - Priorização de Requisitos:
              - Emissões Atmosféricas: modulos/newave/priorizacao/emissoes.md
              - Ruídos: modulos/newave/priorizacao/ruidos.md
              - Erosão: modulos/newave/priorizacao/erosao.md
          - Histórias de Usuário:
              - Emissões Atmosféricas: modulos/newave/modelagem/emissoes.md
              - Ruídos: modulos/newave/modelagem/ruidos.md
              - Erosão: modulos/newave/modelagem/erosao.md
          - Backlog: modulos/newave/backlog_geral.md
      - AXS:
          - Discovery:
              - 16/06 - Pré-Plantio: modulos/axs/discovery/plantio.md
              - 23/07 - PRAD: modulos/axs/discovery/prad.md
          - Elicitação de Requisitos:
              - PRAD: modulos/axs/elicitacao/prad.md
              - Plantio: modulos/axs/elicitacao/plantio.md
          - Priorização de Requisitos:
              - PRAD: modulos/axs/priorizacao/prad.md
              - Plantio: modulos/axs/priorizacao/plantio.md
          - Histórias de Usuário:
              - PRAD: modulos/axs/modelagem/prad.md
              - Plantio: modulos/axs/modelagem/plantio.md
          - Backlog: modulos/axs/backlog_geral.md
      - Engeform:
          - Discovery:
              - 28/07 - Meio Socio: modulos/engeform/discovery/engeform.md
          - Elicitação de Requisitos: modulos/engeform/elicitacao/engeform.md
          - Priorização de Requisitos: modulos/engeform/priorizacao/engeform.md
          - Histórias de Usuário: modulos/engeform/modelagem/engeform.md
          - Fichas de Coleta: modulos/engeform/fichas_coleta/engeform.md 
  - Rastreabilidade:
      - Matriz de Rastreabilidade: rastreabilidade/matriz.md
